services:
  werkint_log.repo.log:
    class:            Werkint\Bundle\LogBundle\Entity\LogRepository
    factory_service:  doctrine.orm.entity_manager
    factory_method:   getRepository
    arguments: [WerkintLogBundle:Log]
