parameters:
  werkint_log.logger.serializerhandler.class:
    Werkint\Bundle\LogBundle\Service\Logger\SerializerHandler
  werkint_log.logger.doctrinehandler.class:
    Werkint\Bundle\LogBundle\Service\Logger\DoctrineHandler
  werkint_log.logger.annotation_driver.class:
    Werkint\Bundle\LogBundle\Service\Logger\Metadata\AnnotationDriver
  werkint_log.logger.metadata_factory.class:
    Metadata\MetadataFactory
  werkint_log.logger.pointcut.class:
    Werkint\Bundle\LogBundle\Service\Logger\Pointcut\LoggerPointcut
  werkint_log.logger.interceptor.class:
    Werkint\Bundle\LogBundle\Service\Logger\Pointcut\PointcutInterceptor

services:
  werkint_log.logger.serializerhandler:
    class: %werkint_log.logger.serializerhandler.class%
    arguments:
      - @doctrine.orm.entity_manager
    tags:
      - { name: jms_serializer.handler, type: Werkint\Bundle\LogBundle\Service\Logger\LoggableObjectInterface, direction: deserialization, format: json, method: deserializeFromJson }

  werkint_log.logger.doctrinehandler:
    class: %werkint_log.logger.doctrinehandler.class%
    arguments:
      - @doctrine

  werkint_log.logger.annotation_driver:
    class: %werkint_log.logger.annotation_driver.class%
    arguments:
      - @annotation_reader
  werkint_log.logger.metadata_factory:
    class: %werkint_log.logger.metadata_factory.class%
    arguments:
      - @werkint_log.logger.annotation_driver
  werkint_log.logger.pointcut:
    class: %werkint_log.logger.pointcut.class%
    arguments:
      - @werkint_log.logger.metadata_factory
    tags:
      - { name: jms_aop.pointcut, interceptor: werkint_log.logger.interceptor }
  werkint_log.logger.interceptor:
    class: %werkint_log.logger.interceptor.class%
    arguments:
      - @werkint_log.logger.metadata_factory
      # TODO: rename
      - @monolog.logger.finance
