parameters:
  werkint_log.logger.serializerhandler.class:
    Werkint\Bundle\LogBundle\Service\Logger\SerializerHandler

services:
  werkint_log.logger.serializerhandler:
    class: %werkint_log.logger.serializerhandler.class%
    arguments:
      - @doctrine.orm.entity_manager
    tags:
      - { name: jms_serializer.handler, type: Werkint\Bundle\LogBundle\Service\Logger\LoggableObjectInterface, direction: deserialization, format: json, method: deserializeFromJson }

  werkint_log.logger.doctrinehandler:
    class: Werkint\Bundle\LogBundle\Service\Logger\DoctrineHandler
    arguments:
      - @doctrine

  werkint_log.logger.annotation_driver:
    class: Werkint\Bundle\LogBundle\Service\Logger\Metadata\AnnotationDriver
    arguments:
      - @annotation_reader
  werkint_log.logger.metadata_factory:
    class: Metadata\MetadataFactory
    arguments:
      - @werkint_log.logger.annotation_driver
  werkint_log.logger.pointcut:
    class: Werkint\Bundle\LogBundle\Service\Logger\Pointcut\LoggerPointcut
    arguments:
      - @werkint_log.logger.metadata_factory
    tags:
      - { name: jms_aop.pointcut, interceptor: werkint_log.logger.interceptor }
  werkint_log.logger.interceptor:
    class: Werkint\Bundle\LogBundle\Service\Logger\Pointcut\PointcutInterceptor
    arguments:
      - @werkint_log.logger.metadata_factory
      - @monolog.logger.finance # TODO: rename
