services:
  werkint_log.logger.doctrinehandler:
    class: Werkint\Bundle\LogBundle\Service\Logger\DoctrineHandler
    arguments:
      - @doctrine

  werkint_log.logger.annotation_driver:
    class: Werkint\Bundle\LogBundle\Service\Logger\Metadata\AnnotationDriver
    arguments:
      - @annotation_reader
  werkint_log.logger.metadata_factory:
    class: Metadata\MetadataFactory
    arguments:
      - @werkint_log.logger.annotation_driver
  werkint_log.logger.pointcut:
    class: Werkint\Bundle\LogBundle\Service\Logger\Pointcut\LoggerPointcut
    arguments:
      - @werkint_log.logger.metadata_factory
    tags:
      - { name: jms_aop.pointcut, interceptor: werkint_log.logger.interceptor }
  werkint_log.logger.interceptor:
    class: Werkint\Bundle\LogBundle\Service\Logger\Pointcut\PointcutInterceptor
    arguments:
      - @werkint_log.logger.metadata_factory
      - @monolog.logger.finance # TODO: rename
